# Generated by Django 3.2.16 on 2023-06-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_link', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlelink',
            name='url',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
