# Generated by Django 3.2.16 on 2023-06-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_link', '0002_articlelink_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelink',
            name='url',
            field=models.CharField(default='', max_length=400),
        ),
    ]
