# Generated by Django 3.2.16 on 2023-06-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_link', '0003_alter_articlelink_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelink',
            name='url',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
