# Generated by Django 3.2.15 on 2022-11-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_auto_20221128_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
