# Generated by Django 3.2.16 on 2023-06-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_feature_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
