# Generated by Django 3.2.16 on 2023-06-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_feature_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
