# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-24 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article_list_item', '0007_auto_20180424_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelistitemplugin',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='article_list_item_articlelistitemplugin', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
