# Generated by Django 2.2.16 on 2020-10-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_list_item', '0008_auto_20200824_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelistitemplugin',
            name='image',
            field=models.ImageField(blank=True, upload_to='articles/thumbs'),
        ),
    ]
