# Generated by Django 3.2.16 on 2023-06-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20230605_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='okimage',
            name='show_caption',
            field=models.BooleanField(default=False),
        ),
    ]
