# Generated by Django 3.2.16 on 2023-06-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image", "0004_okimage_in_gallery"),
    ]

    operations = [
        migrations.AddField(
            model_name="okimage",
            name="text_black",
            field=models.BooleanField(default=False),
        ),
    ]
