# Generated by Django 3.2.16 on 2023-06-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image", "0006_okimage_full_width"),
    ]

    operations = [
        migrations.AddField(
            model_name="okimage",
            name="in_carousel",
            field=models.BooleanField(default=False),
        ),
    ]
