# Generated by Django 4.2.3 on 2023-08-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image", "0008_alter_okimage_cmsplugin_ptr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="okimage",
            name="show_caption",
            field=models.BooleanField(
                default=False, verbose_name="Use caption instead of text"
            ),
        ),
    ]
