# Generated by Django 4.2.3 on 2023-08-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image", "0009_alter_okimage_show_caption"),
    ]

    operations = [
        migrations.AddField(
            model_name="okimage",
            name="is_logo",
            field=models.BooleanField(default=False),
        ),
    ]
