# Generated by Django 4.2.3 on 2024-01-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iframe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iframeplugin',
            name='height',
            field=models.CharField(default='100%', help_text='e.g. 100% or 500px', max_length=10),
        ),
        migrations.AlterField(
            model_name='iframeplugin',
            name='style',
            field=models.CharField(blank=True, help_text='e.g. border: 1px solid black;', max_length=100),
        ),
        migrations.AlterField(
            model_name='iframeplugin',
            name='width',
            field=models.CharField(default='100%', help_text='e.g. 100% or 500px', max_length=10),
        ),
    ]
