# Generated by Django 4.2.3 on 2024-01-09 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iframe', '0002_alter_iframeplugin_height_alter_iframeplugin_style_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iframeplugin',
            options={'verbose_name': 'iframe', 'verbose_name_plural': 'iframes'},
        ),
    ]
