# Generated by Django 4.2.3 on 2023-08-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hero_punch", "0002_alter_heropunch_cmsplugin_ptr"),
    ]

    operations = [
        migrations.AddField(
            model_name="heropunch",
            name="banner_type",
            field=models.CharField(
                choices=[
                    ("default", "Default"),
                    ("opening_default", "Opening Default"),
                    ("opening_center", "Opening Center"),
                    ("cta_newsletter", "Newsletter"),
                ],
                default="default",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="heropunch",
            name="text",
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name="heropunch",
            name="url",
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name="heropunch",
            name="url_text",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
