# Generated by Django 4.2.3 on 2023-08-18 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "hero_punch",
            "0003_heropunch_banner_type_heropunch_text_heropunch_url_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="heropunch",
            name="banner_type",
            field=models.CharField(
                choices=[
                    ("default", "Default"),
                    ("opening_default", "Opening Default"),
                    ("opening_center", "Opening Center"),
                ],
                default="default",
                max_length=15,
            ),
        ),
    ]
