# Generated by Django 4.2.3 on 2023-07-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("number_stat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="numberstat",
            name="columns",
            field=models.CharField(
                choices=[("single", "Single"), ("multiple", "Multiple")],
                default="1",
                max_length=15,
            ),
        ),
    ]
