# Generated by Django 3.2.16 on 2023-06-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("header", "0002_auto_20230530_1547"),
    ]

    operations = [
        migrations.AddField(
            model_name="header",
            name="header_type",
            field=models.CharField(
                choices=[
                    ("h1", "Text top / Image left / Long text right"),
                    ("h2", "Image left / Text right"),
                ],
                default="h1",
                max_length=3,
            ),
        ),
    ]
