# Generated by Django 4.2.3 on 2023-11-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardperson',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
