# Generated by Django 3.2.16 on 2023-06-02 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='video_video', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=200)),
                ('video_image', models.ImageField(upload_to='video/images')),
                ('video_id', models.CharField(default='', max_length=400)),
                ('video_alt', models.CharField(default='', max_length=400)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
