# Generated by Django 3.2.16 on 2023-06-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="video_caption",
            field=models.CharField(default="", max_length=400),
        ),
    ]
