# Generated by Django 3.2.16 on 2023-06-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("full_banner", "0002_auto_20230602_1703"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fullbanner",
            name="banner_alt",
            field=models.CharField(blank=True, default="", max_length=400),
        ),
        migrations.AlterField(
            model_name="fullbanner",
            name="banner_button_text",
            field=models.CharField(blank=True, default="", max_length=400),
        ),
        migrations.AlterField(
            model_name="fullbanner",
            name="banner_link",
            field=models.CharField(blank=True, default="", max_length=400),
        ),
        migrations.AlterField(
            model_name="fullbanner",
            name="banner_text",
            field=models.CharField(blank=True, default="", max_length=400),
        ),
        migrations.AlterField(
            model_name="fullbanner",
            name="banner_text_strong",
            field=models.CharField(blank=True, default="", max_length=400),
        ),
    ]
