# Generated by Django 3.2.16 on 2023-06-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("full_banner", "0003_auto_20230616_0834"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fullbanner",
            name="banner_picture",
            field=models.ImageField(blank=True, null=True, upload_to="banner/images"),
        ),
    ]
