# Generated by Django 3.2.16 on 2023-06-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("full_banner", "0004_alter_fullbanner_banner_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fullbanner",
            name="banner_background",
            field=models.ImageField(blank=True, null=True, upload_to="banner/images"),
        ),
    ]
