# Generated by Django 4.2.3 on 2023-08-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banner", "0002_alter_banner_cmsplugin_ptr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="banner_type",
            field=models.CharField(
                choices=[
                    ("warning", "warning"),
                    ("success", "success"),
                    ("error", "error"),
                    ("info", "info"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
