# Generated by Django 3.2.16 on 2023-06-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_block', '0002_auto_20230603_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureblock',
            name='url',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
