<<<<<<< HEAD
# Generated by Django 4.2.3 on 2023-08-16 06:13
=======
# Generated by Django 4.2.3 on 2023-08-09 09:13
>>>>>>> Add new types to feature plugin

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feature_block", "0008_alter_featureblock_cmsplugin_ptr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featureblock",
            name="block_type",
            field=models.CharField(
                choices=[
<<<<<<< HEAD
                    ("yellow_box", "Yellow Box"),
                    ("white_box", "White Box"),
                    ("transparent_title", "Transparent with Title"),
                    ("transparent", "Transparent"),
=======
                    ("yellow", "Yellow"),
                    ("white", "White"),
                    ("transparent_title", "Transparent with Title"),
                    ("transparent_no_title", "Transparent without Title"),
>>>>>>> Add new types to feature plugin
                    ("background_rounded", "Rounded corners"),
                    ("blue", "Blue Background"),
                    ("yellow", "Yellow Background"),
                    ("purple", "Purple Background"),
                ],
                default="yellow",
                max_length=20,
            ),
        ),
    ]
