# Generated by Django 4.2.3 on 2023-08-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feature_block", "0009_alter_featureblock_block_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="featureblock",
            name="text_color",
            field=models.CharField(
                choices=[("black", "Black"), ("white", "White")],
                default="black",
                max_length=10,
            ),
        ),
    ]
