# Generated by Django 4.2.3 on 2023-08-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feature_block", "0009_alter_featureblock_block_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featureblock",
            name="block_type",
            field=models.CharField(
                choices=[
                    ("yellow", "Yellow"),
                    ("white", "White"),
                    ("transparent_title", "Transparent with Title"),
                    ("transparent_no_title", "Transparent without Title"),
                    ("background_rounded", "Rounded corners"),
                    ("header_background", "Header Background"),
                    ("blue", "Blue Background"),
                    ("yellow", "Yellow Background"),
                    ("purple", "Purple Background"),
                ],
                default="yellow",
                max_length=20,
            ),
        ),
    ]
