# Generated by Django 4.2.3 on 2023-08-22 08:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feature_block", "0010_featureblock_text_color"),
        ("feature_block", "0011_featureblockcontainer"),
    ]

    operations = []
