# Generated by Django 4.2.3 on 2023-09-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feature_block", "0013_alter_featureblock_block_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="featureblockcontainer",
            name="show_title",
            field=models.BooleanField(default=False),
        ),
    ]
