# Generated by Django 3.2.16 on 2023-06-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="heading",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="text",
            field=models.TextField(blank=True),
        ),
    ]
