# Generated by Django 3.2.16 on 2023-06-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20230615_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='button_label',
            field=models.CharField(blank=True, default='Subscribe', max_length=200),
        ),
    ]
