# Generated by Django 3.2.16 on 2023-06-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0003_newsletter_button_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="campaign_type",
            field=models.CharField(
                choices=[
                    ("newsletter", "Newsletter"),
                    ("campaign", "Campaign"),
                    ("small", "Small"),
                ],
                default="newsletter",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="image",
            field=models.ImageField(blank=True, upload_to="campaign/images"),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="image_alt",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
