# Generated by Django 4.2.3 on 2023-07-24 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentList',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(blank=True, max_length=400)),
                ('date', models.CharField(blank=True, default='', max_length=200)),
                ('date_number', models.CharField(blank=True, default='', max_length=200)),
                ('url', models.CharField(blank=True, default='', max_length=400)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
