# Generated by Django 3.2.16 on 2023-06-29 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spotlight',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='spotlight_spotlight', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('text', models.CharField(blank=True, max_length=500)),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('alignment', models.CharField(choices=[('center', 'Center'), ('left', 'Left'), ('right', 'Right')], default='center', max_length=6)),
                ('color', models.CharField(choices=[('black', 'Black'), ('white', 'White')], default='white', max_length=16)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='spotlight/images')),
                ('image_alt', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
