# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-24 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0013_update_country_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproject',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='organisation_featuredproject', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='featuredtheme',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='organisation_featuredtheme', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='networkgrouplist',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='organisation_networkgrouplist', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='projectlist',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='organisation_projectlist', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='signupform',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='organisation_signupform', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
