# Generated by Django 3.2.16 on 2023-06-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0016_auto_20201028_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkgroup',
            name='country_flag',
            field=models.ImageField(blank=True, upload_to='organisation/network/chapter'),
        ),
    ]
