# Generated by Django 3.2.16 on 2023-06-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0017_networkgroup_country_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkgroup',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='networkgroup',
            name='mastodon_url',
            field=models.URLField(blank=True),
        ),
    ]
