# Generated by Django 4.2.3 on 2023-07-17 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0019_alter_featuredproject_cmsplugin_ptr_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="featuredtheme",
            name="cmsplugin_ptr",
        ),
        migrations.RemoveField(
            model_name="featuredtheme",
            name="theme",
        ),
        migrations.RemoveField(
            model_name="projectlist",
            name="cmsplugin_ptr",
        ),
        migrations.RemoveField(
            model_name="projectlist",
            name="project_type",
        ),
        migrations.RemoveField(
            model_name="projectlist",
            name="theme",
        ),
        migrations.RemoveField(
            model_name="project",
            name="themes",
        ),
        migrations.RemoveField(
            model_name="workinggroup",
            name="themes",
        ),
        migrations.DeleteModel(
            name="FeaturedProject",
        ),
        migrations.DeleteModel(
            name="FeaturedTheme",
        ),
        migrations.DeleteModel(
            name="ProjectList",
        ),
        migrations.DeleteModel(
            name="Theme",
        ),
    ]
