# Generated by Django 4.2.3 on 2023-07-21 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0021_delete_project_delete_projecttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkgroup',
            name='working_groups',
        ),
        migrations.DeleteModel(
            name='WorkingGroup',
        ),
    ]
