# Generated by Django 4.2.3 on 2023-08-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0022_remove_networkgroup_working_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sidebarextension",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="organisation/sidebar/images"
            ),
        ),
    ]
