# Generated by Django 4.2.3 on 2024-06-11 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0023_sidebarextension_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitmembership',
            name='person',
        ),
        migrations.RemoveField(
            model_name='unitmembership',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.DeleteModel(
            name='UnitMembership',
        ),
    ]
