# Generated by Django 4.2.3 on 2024-06-11 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0025_remove_boardmembership_board_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkgrouplist',
            name='cmsplugin_ptr',
        ),
        migrations.RemoveField(
            model_name='networkgroupmembership',
            name='networkgroup',
        ),
        migrations.RemoveField(
            model_name='networkgroupmembership',
            name='person',
        ),
        migrations.DeleteModel(
            name='NetworkGroup',
        ),
        migrations.DeleteModel(
            name='NetworkGroupList',
        ),
        migrations.DeleteModel(
            name='NetworkGroupMembership',
        ),
    ]
