# Generated by Django 4.2.3 on 2024-06-11 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0026_remove_networkgrouplist_cmsplugin_ptr_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NowDoing',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
