# Generated by Django 4.2.3 on 2023-08-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0002_alter_gallery_cmsplugin_ptr"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="gallery_type",
            field=models.CharField(
                choices=[
                    ("image_slider", "Image Slider"),
                    ("logo_static", "Static Logo"),
                ],
                default="image_slider",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="gallery",
            name="url",
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name="gallery",
            name="url_text",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
