# Generated by Django 4.2.3 on 2023-08-30 07:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0003_gallery_circle_position_gallery_color_gallery_size"),
        ("gallery", "0003_gallery_gallery_type_gallery_url_gallery_url_text"),
    ]

    operations = []
