# Generated by Django 4.2.3 on 2023-09-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0005_alter_gallery_gallery_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="gallery_type",
            field=models.CharField(
                choices=[
                    ("image_slider", "Image Slider"),
                    ("logo_static", "Static Logo"),
                    ("in_column", "In Column"),
                ],
                default="image_slider",
                max_length=20,
            ),
        ),
    ]
