# Generated by Django 4.2.3 on 2023-08-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grid_columns", "0002_alter_gridcolumns_cmsplugin_ptr"),
    ]

    operations = [
        migrations.AddField(
            model_name="gridcolumns",
            name="skip_columns",
            field=models.IntegerField(default=0),
        ),
    ]
