#!/bin/bash

set -eu

echo "Present in virtualenv but not in requirements.txt:" >&2
echo >&2

comm -23 <(pip freeze | sort) <(sort -u requirements.txt)

echo >&2
echo >&2
echo "Present in virtualenv but not in requirements.txt or requirements.dev.txt:" >&2
echo >&2

comm -23 <(pip freeze | sort) <(sort -u requirements.txt requirements.dev.txt)
