# Generated by Django 3.2.16 on 2023-06-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heading', '0004_alter_heading_heading_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='heading',
            name='alignment',
            field=models.CharField(choices=[('center', 'Center'), ('left', 'Left'), ('right', 'Right')], default='center', max_length=6),
        ),
    ]
