# Generated by Django 4.2.3 on 2023-08-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("heading", "0007_alter_heading_cmsplugin_ptr"),
    ]

    operations = [
        migrations.AddField(
            model_name="heading",
            name="anchor_id",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="heading",
            name="is_anchor",
            field=models.BooleanField(default=False),
        ),
    ]
