# Generated by Django 4.2.3 on 2023-08-23 11:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("heading", "0008_heading_anchor_id_heading_is_anchor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="heading",
            name="is_anchor",
        ),
    ]
