name: Run tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements.dev.txt

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Ensure JS and CSS are up-to-date
        run: |
          echo "Runnign npm install"
          npm install
          echo "Running grunt"
          npx grunt uglify:scripts
          echo "Running npm run build"
          npm run build
          # echo "Running git diff"
          # git diff --exit-code static/

      - name: Django check
        run: python manage.py check --settings=foundation.settings

      - name: Ensure migrations are up-to-date
        run: |
          # show migrations
          python manage.py makemigrations --dry-run --verbosity 3
          # run manually a migration for plugin
          # See https://github.com/django-cms/djangocms-picture/issues/122
          python manage.py makemigrations djangocms_picture
          # check migrations
          python manage.py makemigrations --check

      - name: Run tests
        run: |
          coverage run manage.py test
          coverage xml

      - name: Check coding standards
        run: flake8 .

      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
